### ISSUE TITLE
IE Testing

### ISSUE THREAD

**Issue by gvsboy** [gvsboy/ghostcube#3]
Give this a whirl in IE. Provide graceful fallbacks in old IE.

**Comment by emersonyu** [comment]
Not working for me in Netscape 4.

**Comment by gvsboy** [comment]
Added the blink element to enable Netscape support.

**Comment by gvsboy** [comment]
Created a fallback for IE10 and IE11. Perhaps Spartan will support preserve-3d.

IE < 10 is out of scope, dog.
